Algoritmo "Teste_Algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/07/2022
Var
   NOME:CARACTERE
   SALARIO: REAL
   IDADE:  INTEIRO


Inicio
      NOME <- "LUCIANO"
      salario <- 2500,00
      idade <- 31
      escreval (NOME)
      escreval (SALARIO)
      escreval (IDADE)


Fimalgoritmo