Algoritmo "Questão 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/08/2022
Var
  Nome: caractere
  


Inicio

    Escreval ("Qual O seu nome?")
    leia (nome)
    
    escreval ("Olá " ,nome,", é um prazer te conhecer!")
    


Fimalgoritmo