Algoritmo "enquanto 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/08/2022
Var

  num: real


Inicio

      num <- 100
   enquanto num >= 0 faca
            escreva (num)
            num <- num - 5

    fimenquanto


Fimalgoritmo