Algoritmo "Questão 1"




Var

   Numero1: inteiro
   Numero2: inteiro
   soma: inteiro
   

Inicio

Escreval ("Digite um número: ")
         leia (numero1)
escreval ("Digite outro número: ")
         leia (numero2)
se (numero1 > numero2) entao
   escreval ("O primeiro valor é o maior!")
senao
     se (numero2 > numero1) entao
     escreval ("O segundo número é o maior!")
     senao numero1 = numero2 entao
     escreval ("Não existe valor maior, os dois são iguais")
fimse
fimse
Fimalgoritmo