Algoritmo "exercicio 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/08/2022
Var
// Seção de Declarações das variáveis 
contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contadora de 100 ate 0 passo -10 faca
escreval (contadora)
fimpara
Fimalgoritmo