Algoritmo "exercicio 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/08/2022
Var

contadora: inteiro
num: inteiro
soma: inteiro

Inicio
escreval ("Digite um número: ")
         leia (num)

para contadora de 1 ate 10 passo 1 faca
soma:= (num*contadora)
escreval (num, " x ", contadora, "= ",soma)
fimpara

Fimalgoritmo