Algoritmo "repita simples"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2022
Var
// Seção de Declarações das variáveis 
   idade: real

Inicio
repita
      escreval ("Qual sua idade?")
      leia (idade)
      ate (idade > 10)


Fimalgoritmo