Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/08/2022
Var

num: inteiro
tabuada: inteiro

Inicio

num:= 1
escreval ("", num,"x5", tabuada)
repita
tabuada:= num*5
num:= num + 1
ate (num > 10)




Fimalgoritmo