Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2022
Var

  soma: real
  num,n1: real

Inicio

num <- 1
repita
escreval ("numero")
         leia (n1)
      soma:= (5*n1)
      escreval ("5 x", n1, "=", soma)
      num <- num + 1
   ate (num > 10)

Fimalgoritmo